### ISSUE TITLE
Maybe change containers/list to implementations on generics

### ISSUE THREAD

**Issue by mr-tron** [Code-Hex/go-generics-cache#16]
https://github.com/bahlo/generic-list-go - for example this looks very similar to containers/list but without empty interfaces.
I noticed what the library uses containers/list because my program sometimes crashes
```
panic: interface conversion: interface {} is nil, not *lru.entry[string,*github.com/Code-Hex/go-generics-cache.Item[string,int64]]

goroutine 241845 [running]:
github.com/Code-Hex/go-generics-cache/policy/lru.(*Cache[...]).delete(...)
 /go/pkg/mod/github.com/!code-!hex/go-generics-cache@v0.0.8/policy/lru/lru.go:118
github.com/Code-Hex/go-generics-cache/policy/lru.(*Cache[...]).deleteOldest(0xc000234330?)
 /go/pkg/mod/github.com/!code-!hex/go-generics-cache@v0.0.8/policy/lru/lru.go:113 +0xed
github.com/Code-Hex/go-generics-cache/policy/lru.(*Cache[...]).Set(0xc00023a048, {0xc0061324b0, 0x42}, 0xc007a885a0)
 /go/pkg/mod/github.com/!code-!hex/go-generics-cache@v0.0.8/policy/lru/lru.go:85 +0x339
github.com/Code-Hex/go-generics-cache.(*Cache[...]).Set(0xc0002340f0, {0xc0061324b0, 0x42}, 0x48, {0x0?, 0x0, 0x0})
 /go/pkg/mod/github.com/!code-!hex/go-generics-cache@v0.0.8/cache.go:158 +0x1f3
 ```
 It also can be problem in logic (maybe some races)

**Comment by Code-Hex** [comment]
@mr-tron Thanks for your reporting.
Do you have a minimal code that is reproduced the problem?

**Comment by mr-tron** [comment]
No. But i use only get and set functions in parallel threads.
I will try to reproduce later.

**Comment by Code-Hex** [comment]
@mr-tron I see in parallel.
Thanks a lot!
> I will try to reproduce later

**Comment by mr-tron** [comment]
MVP. golang 1.18rc1
```golang
package main

import (
	cache "github.com/Code-Hex/go-generics-cache"
	"github.com/Code-Hex/go-generics-cache/policy/lru"
	"math/rand"
	"time"
)

var c *cache.Cache[int, int]
func main() {
	c = cache.New(cache.AsLRU[int, int](lru.WithCapacity(10000)))
	for i:= int64(0) ; i < 10 ; i++ {
		go func(i int64) {
			m := rand.New(rand.NewSource(i))
			for {
				c.Set(m.Intn(100000), m.Intn(100000))
				c.Get(m.Intn(100000))
			}
		}(i)
	}
	time.Sleep(time.Minute*10)
}

```
it usually fails for me in few minutes

**Comment by Code-Hex** [comment]
@mr-tron Thanks! I fixed at https://github.com/Code-Hex/go-generics-cache/pull/17
