### ISSUE TITLE
Panic when delete expired items.

### ISSUE THREAD

**Issue by chenyanchen** [Code-Hex/go-generics-cache#39]
<details>
<summary>go env</summary>

```bash
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/91/6ypxbjvs1_3007pts7zflvwh0000gn/T/go-build1223268749=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details>
<summary>main.go</summary>

```go
package main

import (
	"time"

	cache "github.com/Code-Hex/go-generics-cache"
	"github.com/Code-Hex/go-generics-cache/policy/lfu"
)

func main() {
	c := cache.New(
		cache.AsLFU[string, string](lfu.WithCapacity(3)),
		cache.WithJanitorInterval[string, string](time.Second),
	)
	c.Set("key1", "value1", cache.WithExpiration(time.Second))
	c.Set("key2", "value3", cache.WithExpiration(time.Second))
	time.Sleep(time.Minute)
}
```

</details>

<details>
<summary>go run main.go</summary>

```bash
$ go run main.go                   
panic: runtime error: index out of range [-1]

goroutine 17 [running]:
github.com/Code-Hex/go-generics-cache/policy/lfu.priorityQueue[...].Swap(...)
        /Users/cyc/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.0/policy/lfu/priotiry_queue.go:53
container/heap.Remove({0x104545080, 0x140000a6018}, 0xffffffffffffffff)
        /opt/homebrew/opt/go/libexec/src/container/heap/heap.go:71 +0x54
github.com/Code-Hex/go-generics-cache/policy/lfu.(*Cache[...]).Delete(0x1045457e0, {0x1045154ce, 0x4})
        /Users/cyc/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.0/policy/lfu/lfu.go:95 +0x5c
github.com/Code-Hex/go-generics-cache.(*Cache[...]).DeleteExpired(0x104545660)
        /Users/cyc/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.0/cache.go:228 +0xf8
github.com/Code-Hex/go-generics-cache.(*janitor).run.func1()
        /Users/cyc/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.0/janitor.go:39 +0xe8
created by github.com/Code-Hex/go-generics-cache.(*janitor).run
        /Users/cyc/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.0/janitor.go:33 +0x78
exit status 2
```

</details>

**Comment by chenyanchen** [comment]
I reviewed this issue #33 and confirm no comlete fixed in #35 .
