### ISSUE TITLE
Nil panic in janitor

### ISSUE THREAD

**Issue by maelick** [Code-Hex/go-generics-cache#46]
After updating dependencies in a project and moving from go-generic-cache 1.1.0 to 1.3.1, I had the pipeline failing with the following nil panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x102dffd]

goroutine 375 [running]:
github.com/Code-Hex/go-generics-cache/policy/simple.(*Cache[...]).Keys.func1(0x3)
	/home/vsts/agents/3.236.1/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.1/policy/simple/simple.go:53 +0x15d
sort.order2_func(...)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sort/zsortfunc.go:299
sort.median_func({0xc00007bd08?, 0xc00038b290?}, 0x3, 0x6, 0x9, 0xc00007bb50)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sort/zsortfunc.go:308 +0x53
sort.choosePivot_func({0xc00007bd08?, 0xc00038b290?}, 0x0, 0xf)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sort/zsortfunc.go:284 +0x190
sort.pdqsort_func({0xc00007bd08?, 0xc00038b290?}, 0x0, 0xf, 0x4)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sort/zsortfunc.go:89 +0x148
sort.Slice({0x15a36e0, 0xc0024d9878}, 0xc00007bd08)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sort/slice.go:29 +0xab
github.com/Code-Hex/go-generics-cache/policy/simple.(*Cache[...]).Keys(0x19a8e60)
	/home/vsts/agents/3.236.1/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.1/policy/simple/simple.go:50 +0x3a5
github.com/Code-Hex/go-generics-cache.(*Cache[...]).DeleteExpired(0x19a99e0)
	/home/vsts/agents/3.236.1/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.1/cache.go:220 +0x6c
github.com/Code-Hex/go-generics-cache.(*janitor).run.func1()
	/home/vsts/agents/3.236.1/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.1/janitor.go:39 +0x202
created by github.com/Code-Hex/go-generics-cache.(*janitor).run in goroutine 1
	/home/vsts/agents/3.236.1/go/pkg/mod/github.com/!code-!hex/go-generics-cache@v1.3.1/janitor.go:33 +0xd1
```

This is the code that uses the cache:
```
	lastHeard, found := c.lastHeardCache.Get(key)
	if found {
		return lastHeard, nil
	}
	lastHeard, err := c.getLastHeard(ctx, key)
	if err != nil {
		return 0, err
	}
	c.lastHeardCache.Set(key, lastHeard, cache.WithExpiration(c.cacheTTL))
```

With the cache being initialized without any option: `cache.New[lastHeardKey, int64]()`

I was also able to reproduce the error with 1.2.0.

The issue does not appear when running my tests locally, only in a pipeline. They use concurrency quite a lot and are significantly slower in the pipeline, possibly explaining why the error does not occur locally. From what I could find in the code, it seems a key has been deleted in the middle of a call to sort, which makes the sort func panic. I can't figure out though why this happens as everything seems protected by a mutex in cache.go.

**Comment by Code-Hex** [comment]
@maelick Thanks for created issue!

I fixed the cache clear logic at https://github.com/Code-Hex/go-generics-cache/pull/48

I have released v1.4.0. So, If you have this issue yet, I will re-open this issue!
